---
- name: Use default upload_tmp_dir in php.ini
  replace: dest=/etc/php/7.0/fpm/php.ini regexp='^upload_tmp_dir.*$' replace='; upload_tmp_dir = /php/cache/upload_tmp' backup=yes
  notify: restart php7.0-fpm

- name: Set allow_url_fopen in php.ini
  replace: dest=/etc/php/7.0/fpm/php.ini regexp='^allow_url_fopen.*$' replace='allow_url_fopen = On' backup=yes
  notify: restart php7.0-fpm

- name: Copy php-fpm configuration
  template: src=site.conf.j2 dest="/etc/php/7.0/fpm/pool.d/{{ web_folder }}.conf"
  notify: restart php7.0-fpm
