---
- stat:
    path: /etc/init.d/php5-fpm
  register: php5

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
  when: php5 is defined

- name: restart php-fpm
  service:
    name: php7.0-fpm
    state: restarted
  when: php5 is not defined

